server:
  port: 8084

spring:
  application:
    name: service-provide-feign
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.mashensoft: debug
